#ifndef ENFILEIRADOR_H
#define ENFILEIRADOR_H

#include "cmsis_os.h" 

#define SIGNAL_ENFILEIRADOR_BOTAO_INTERNO_T 0x0001
#define SIGNAL_ENFILEIRADOR_BOTAO_INTERNO_1 0x0002
#define SIGNAL_ENFILEIRADOR_BOTAO_INTERNO_2 0x0004
#define SIGNAL_ENFILEIRADOR_BOTAO_INTERNO_3 0x0008
#define SIGNAL_ENFILEIRADOR_BOTAO_SOBE_T 0x0010
#define SIGNAL_ENFILEIRADOR_BOTAO_SOBE_1 0x0020
#define SIGNAL_ENFILEIRADOR_BOTAO_SOBE_2 0x0040
#define SIGNAL_ENFILEIRADOR_BOTAO_DESCE_1 0x0080
#define SIGNAL_ENFILEIRADOR_BOTAO_DESCE_2 0x0100
#define SIGNAL_ENFILEIRADOR_BOTAO_DESCE_3 0x0200

#define REQUISICAO_BOTAO_INTERNO_T 1
#define REQUISICAO_BOTAO_INTERNO_1 2
#define REQUISICAO_BOTAO_INTERNO_2 3
#define REQUISICAO_BOTAO_INTERNO_3 4
#define REQUISICAO_BOTAO_SOBE_T 5
#define REQUISICAO_BOTAO_SOBE_1 6
#define REQUISICAO_BOTAO_SOBE_2 7
#define REQUISICAO_BOTAO_DESCE_1 8
#define REQUISICAO_BOTAO_DESCE_2 9
#define REQUISICAO_BOTAO_DESCE_3 10

void task_enfileirador(void const *arg);

#endif //ENFILEIRADOR_H
